spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:anbu_db
    driver-class-name: org.h2.Driver
    username: jordan
    password: 1234

swagger:
  basePackage: com.dev.anbu.controller
  regex: /.*
  title: Dev Backend API
  description: Dev backend kpi
  version: 1.0.0

statistics:
  sample: 1
  death-days:
    min: 35000
    max: 45000
